### ISSUE TITLE
Why no approvals or safeTransfer exposed

### ISSUE THREAD

**Issue by hauchu1998** [chiru-labs/PBT#38]
Hi, 

I'm curious why the ERC721ReadOnly.sol wants to disable approval or transfer exposed. Isn't it will be safer if we include the safeTransferFrom feature so that when an item is stolen, the ownership won't be transfer to others?

**Comment by 2pmflow** [comment]
Hey Hau, happy holidays. We disable the traditional 721 transfers in ERC721ReadOnly so that the only way to transfer the token is with a signature through the chip, exposed in the IPBT interface.

**Comment by hauchu1998** [comment]
> Hey Hau, happy holidays. We disable the traditional 721 transfers in ERC721ReadOnly so that the only way to transfer the token is with a signature through the chip, exposed in the IPBT interface.

Hi @2pmflow thanks for your reply. Sorry, I might not be clear enough. My concern is about why you disabled `approve `and `transferFrom` functions with chips. Can't users also `approveWithChip` and `transferFromWithChip`? if someone steals another user's item, they could scan the chip and transfer the ownership to themselves.

I might be wrong but it will be nice if you can help me with this. Thank you so much.

**Comment by 2pmflow** [comment]
> they could scan the chip and transfer the ownership to themselves

This is actually intentional as per the spec- whoever owns the physical owns the NFT. It's out of scope for the spec to prevent irl theft, but from the contract's POV, whoever owns the item owns the NFT. That being said, there are layers and extensions that can be built upon the base PBT primitive, e.g. extending transferWithChip to require an approval or some type of time-related gating.
